image: alpine:latest

before_script:
  - apk -q update
  - apk -q add build-base cmake check-dev git
  - cmake .

stages:
  - build
  - test

job_build:
  stage: build
  script:
    - make SDB
  artifacts:
    expire_in: 1 week
    paths:
      - src/SDB

job_test:
  stage: test
  script:
    - make check_SDB
    - ./tests/check_SDB