image: alpine:latest

before_script:
  - apk -q update
  - apk -q add build-base cmake check-dev git

stages:
  - build
  - test

job_build:
  stage: build
  script:
    - export CC=/usr/bin/x86_64-alpine-linux-musl-gcc
    - cmake -DCMAKE_EXE_LINKER_FLAGS="-static -Os" .
    - make SDB
  artifacts:
    name: SDB Linux
    expire_in: 1 week
    paths:
      - bin/SDB

job_test:
  stage: test
  script:
    - cmake .
    - make check_SDB
    - ./bin/check_SDB